/**
 * Demo presets: pre-generated results replayed when the app runs without a
 * backend (see src/lib/mode.js).
 *
 * To replace a sample with real output, no code changes are needed:
 *   1. Run the app locally in live mode with the preset's ingredients, diet and time.
 *   2. Save the JSON body returned by POST /api/recipes as src/demo/<id>.json
 *      (shape: { "recipes": [Recipe, Recipe, Recipe] }, exactly the server schema).
 *   3. Save one photo per recipe as public/demo/<id>-1.webp, <id>-2.webp, <id>-3.webp
 *      (same order as the recipes). Missing photos show a placeholder instead.
 *
 * The recipes in breakfast.json, chicken.json and tofu.json and the photos in public/demo/
 * were generated by OpenAI models from this app's own prompts (October 2026).
 */
import breakfast from './breakfast.json' with { type: 'json' };
import chicken from './chicken.json' with { type: 'json' };
import tofu from './tofu.json' with { type: 'json' };

/** "./" in the portfolio build, "/" in dev. Falls back to "/" outside Vite (unit tests). */
const BASE_URL = import.meta.env?.BASE_URL ?? '/';

const imagesFor = (id, count) =>
  Array.from({ length: count }, (_, i) => `${BASE_URL}demo/${id}-${i + 1}.webp`);

function preset({ id, label, emoji, ingredients, diet, time, data }) {
  const recipes = Array.isArray(data?.recipes) ? data.recipes : [];
  return { id, label, emoji, ingredients, diet, time, recipes, images: imagesFor(id, recipes.length) };
}

export const presets = [
  preset({
    id: 'breakfast',
    label: 'Eggs · Tomato · Bread',
    emoji: '🍳',
    ingredients: ['eggs', 'tomato', 'bread'],
    diet: 'vegetarian',
    time: 20,
    data: breakfast,
  }),
  preset({
    id: 'chicken',
    label: 'Chicken · Rice · Broccoli',
    emoji: '🍗',
    ingredients: ['chicken thigh', 'rice', 'broccoli', 'garlic', 'soy sauce'],
    diet: 'none',
    time: 30,
    data: chicken,
  }),
  preset({
    id: 'tofu',
    label: 'Tofu · Spinach · Noodles',
    emoji: '🍜',
    ingredients: ['tofu', 'spinach', 'mushrooms', 'garlic', 'noodles'],
    diet: 'vegan',
    time: 25,
    data: tofu,
  }),
];

/** The form starts with this one (the original app's default was "eggs, tomato, bread"). */
export const defaultPreset = presets[0];
